export const NamedColors = [
  //Pink Colors
  { name: "Pink", hex: "#FFC0CB", group: "Pink" },
  { name: "Light Pink", hex: "#FFB6C1", group: "Pink" },
  { name: "Hot Pink", hex: "#FF69B4", group: "Pink" },
  { name: "Deep Pink", hex: "#FF1493", group: "Pink" },
  { name: "Pale Violet Red", hex: "#DB7093", group: "Pink" },
  { name: "Medium Violet Red", hex: "#C71585", group: "Pink" },

  //Purple Colors
  { name: "Lavender", hex: "#E6E6FA", group: "Purple" },
  { name: "Thistle", hex: "#D8BFD8", group: "Purple" },
  { name: "Plum", hex: "#DDA0DD", group: "Purple" },
  { name: "Orchid", hex: "#DA70D6", group: "Purple" },
  { name: "Violet", hex: "#EE82EE", group: "Purple" },
  { name: "Fuchsia", hex: "#FF00FF", group: "Purple" },
  { name: "Magenta", hex: "#FF00FF", group: "Purple" },
  { name: "Medium Orchid", hex: "#BA55D3", group: "Purple" },
  { name: "Dark Orchid", hex: "#9932CC", group: "Purple" },
  { name: "Dark Violet", hex: "#9400D3", group: "Purple" },
  { name: "Blue Violet", hex: "#8A2BE2", group: "Purple" },
  { name: "Dark Magenta", hex: "#8B008B", group: "Purple" },
  { name: "Purple", hex: "#800080", group: "Purple" },
  { name: "Medium Purple", hex: "#9370DB", group: "Purple" },
  { name: "Medium Slate Blue", hex: "#7B68EE", group: "Purple" },
  { name: "Slate Blue", hex: "#6A5ACD", group: "Purple" },
  { name: "Dark Slate Blue", hex: "#483D8B", group: "Purple" },
  { name: "Rebecca Purple", hex: "#663399", group: "Purple" },
  { name: "Indigo", hex: "#4B0082", group: "Purple" },

  //Red Colors
  { name: "Light Salmon", hex: "#FFA07A", group: "Red" },
  { name: "Salmon", hex: "#FA8072", group: "Red" },
  { name: "Dark Salmon", hex: "#E9967A", group: "Red" },
  { name: "Light Coral", hex: "#F08080", group: "Red" },
  { name: "Indian Red", hex: "#CD5C5C", group: "Red" },
  { name: "Crimson", hex: "#DC143C", group: "Red" },
  { name: "Red", hex: "#FF0000", group: "Red" },
  { name: "Fire Brick", hex: "#B22222", group: "Red" },
  { name: "Dark Red", hex: "#8B0000", group: "Red" },

  //Orange Colors
  { name: "Orange", hex: "#FFA500", group: "Orange" },
  { name: "Dark Orange", hex: "#FF8C00", group: "Orange" },
  { name: "Coral", hex: "#FF7F50", group: "Orange" },
  { name: "Tomato", hex: "#FF6347", group: "Orange" },
  { name: "Orange Red", hex: "#FF4500", group: "Orange" },

  //Yellow Colors
  { name: "Gold", hex: "#FFD700", group: "Yellow" },
  { name: "Yellow", hex: "#FFFF00", group: "Yellow" },
  { name: "Light Yellow", hex: "#FFFFE0", group: "Yellow" },
  { name: "Lemon Chiffon", hex: "#FFFACD", group: "Yellow" },
  { name: "Light Golden Rod Yellow", hex: "#FAFAD2", group: "Yellow" },
  { name: "Papaya Whip", hex: "#FFEFD5", group: "Yellow" },
  { name: "Moccasin", hex: "#FFE4B5", group: "Yellow" },
  { name: "Peach Puff", hex: "#FFDAB9", group: "Yellow" },
  { name: "Pale Golden Rod", hex: "#EEE8AA", group: "Yellow" },
  { name: "Khaki", hex: "#F0E68C", group: "Yellow" },
  { name: "Dark Khaki", hex: "#BDB76B", group: "Yellow" },

  //Green Colors
  { name: "Green Yellow", hex: "#ADFF2F", group: "Green" },
  { name: "Chartreuse", hex: "#7FFF00", group: "Green" },
  { name: "Lawn Green", hex: "#7CFC00", group: "Green" },
  { name: "Lime", hex: "#00FF00", group: "Green" },
  { name: "Lime Green", hex: "#32CD32", group: "Green" },
  { name: "Pale Green", hex: "#98FB98", group: "Green" },
  { name: "Light Green", hex: "#90EE90", group: "Green" },
  { name: "Medium Spring Green", hex: "#00FA9A", group: "Green" },
  { name: "Spring Green", hex: "#00FF7F", group: "Green" },
  { name: "Medium Sea Green", hex: "#3CB371", group: "Green" },
  { name: "Sea Green", hex: "#2E8B57", group: "Green" },
  { name: "Forest Green", hex: "#228B22", group: "Green" },
  { name: "Green", hex: "#008000", group: "Green" },
  { name: "Dark Green", hex: "#006400", group: "Green" },
  { name: "Yellow Green", hex: "#9ACD32", group: "Green" },
  { name: "Olive Drab", hex: "#6B8E23", group: "Green" },
  { name: "Dark Olive Green", hex: "#556B2F", group: "Green" },
  { name: "Medium Aqua Marine", hex: "#66CDAA", group: "Green" },
  { name: "Dark Sea Green", hex: "#8FBC8F", group: "Green" },
  { name: "Light Sea Green", hex: "#20B2AA", group: "Green" },
  { name: "Dark Cyan", hex: "#008B8B", group: "Green" },
  { name: "Teal", hex: "#008080", group: "Green" },

  //Cyan Colors
  { name: "Aqua", hex: "#00FFFF", group: "Cyan" },
  { name: "Cyan", hex: "#00FFFF", group: "Cyan" },
  { name: "Light Cyan", hex: "#E0FFFF", group: "Cyan" },
  { name: "Pale Turquoise", hex: "#AFEEEE", group: "Cyan" },
  { name: "Aquamarine", hex: "#7FFFD4", group: "Cyan" },
  { name: "Turquoise", hex: "#40E0D0", group: "Cyan" },
  { name: "Medium Turquoise", hex: "#48D1CC", group: "Cyan" },
  { name: "Dark Turquoise", hex: "#00CED1", group: "Cyan" },

  //Blue Colors
  { name: "Cadet Blue", hex: "#5F9EA0", group: "Blue" },
  { name: "Steel Blue", hex: "#4682B4", group: "Blue" },
  { name: "Light Steel Blue", hex: "#B0C4DE", group: "Blue" },
  { name: "Light Blue", hex: "#ADD8E6", group: "Blue" },
  { name: "Powder Blue", hex: "#B0E0E6", group: "Blue" },
  { name: "Light Sky Blue", hex: "#87CEFA", group: "Blue" },
  { name: "Sky Blue", hex: "#87CEEB", group: "Blue" },
  { name: "Corn flower Blue", hex: "#6495ED", group: "Blue" },
  { name: "Deep Sky Blue", hex: "#00BFFF", group: "Blue" },
  { name: "Dodger Blue", hex: "#1E90FF", group: "Blue" },
  { name: "Royal Blue", hex: "#4169E1", group: "Blue" },
  { name: "Blue", hex: "#0000FF", group: "Blue" },
  { name: "Medium Blue", hex: "#0000CD", group: "Blue" },
  { name: "Dark Blue", hex: "#00008B", group: "Blue" },
  { name: "Navy", hex: "#000080", group: "Blue" },
  { name: "Midnight Blue", hex: "#191970", group: "Blue" },

  //Brown Colors
  { name: "Cornsilk", hex: "#FFF8DC", group: "Brown" },
  { name: "Blanched Almond", hex: "#FFEBCD", group: "Brown" },
  { name: "Bisque", hex: "#FFE4C4", group: "Brown" },
  { name: "Navajo White", hex: "#FFDEAD", group: "Brown" },
  { name: "Wheat", hex: "#F5DEB3", group: "Brown" },
  { name: "Burly Wood", hex: "#DEB887", group: "Brown" },
  { name: "Tan", hex: "#D2B48C", group: "Brown" },
  { name: "Rosy Brown", hex: "#BC8F8F", group: "Brown" },
  { name: "Sandy Brown", hex: "#F4A460", group: "Brown" },
  { name: "Golden Rod", hex: "#DAA520", group: "Brown" },
  { name: "Dark Golden Rod", hex: "#B8860B", group: "Brown" },
  { name: "Peru", hex: "#CD853F", group: "Brown" },
  { name: "Chocolate", hex: "#D2691E", group: "Brown" },
  { name: "Olive", hex: "#808000", group: "Brown" },
  { name: "Saddle Brown", hex: "#8B4513", group: "Brown" },
  { name: "Sienna", hex: "#A0522D", group: "Brown" },
  { name: "Brown", hex: "#A52A2A", group: "Brown" },
  { name: "Maroon", hex: "#800000", group: "Brown" },

  //White Colors
  { name: "White", hex: "#FFFFFF", group: "White" },
  { name: "Snow", hex: "#FFFAFA", group: "White" },
  { name: "Honey Dew", hex: "#F0FFF0", group: "White" },
  { name: "Mint Cream", hex: "#F5FFFA", group: "White" },
  { name: "Azure", hex: "#F0FFFF", group: "White" },
  { name: "Alice Blue", hex: "#F0F8FF", group: "White" },
  { name: "Ghost White", hex: "#F8F8FF", group: "White" },
  { name: "White Smoke", hex: "#F5F5F5", group: "White" },
  { name: "Sea Shell", hex: "#FFF5EE", group: "White" },
  { name: "Beige", hex: "#F5F5DC", group: "White" },
  { name: "Old Lace", hex: "#FDF5E6", group: "White" },
  { name: "Floral White", hex: "#FFFAF0", group: "White" },
  { name: "Ivory", hex: "#FFFFF0", group: "White" },
  { name: "Antique White", hex: "#FAEBD7", group: "White" },
  { name: "Linen", hex: "#FAF0E6", group: "White" },
  { name: "Lavender Blush", hex: "#FFFFFF", group: "White" },
  { name: "Misty Rose", hex: "#FFE4E1", group: "White" },

  //Grey Colors
  { name: "Gainsboro", hex: "#DCDCDC", group: "Grey" },
  { name: "Light Gray", hex: "#D3D3D3", group: "Grey" },
  { name: "Silver", hex: "#C0C0C0", group: "Grey" },
  { name: "Dark Gray", hex: "#A9A9A9", group: "Grey" },
  { name: "Dim Gray", hex: "#696969", group: "Grey" },
  { name: "Gray", hex: "#808080", group: "Grey" },
  { name: "Light Slate Gray", hex: "#778899", group: "Grey" },
  { name: "Slate Gray", hex: "#708090", group: "Grey" },
  { name: "Dark Slate Gray", hex: "#2F4F4F", group: "Grey" },
  { name: "Black", hex: "#000000", group: "Grey" },
];
